### ISSUE TITLE
Mismatched dependencies

### ISSUE THREAD

**Issue by beenje** [conda-forge/openpiv-feedstock#53]
### Comment:

While looking at another package (pyopenrivercam) that depends on this package, I noticed that the pip dependencies defined in [setup.py](https://github.com/OpenPIV/openpiv-python/blob/0bc247ea020ef7f59d94a53ec951f684c448b717/setup.py#L21) don't match the ones defined for the conda package in [meta.yaml](https://github.com/conda-forge/openpiv-feedstock/blob/449741f5091a54f09a5cb821fba01aa252b4c0f4/recipe/meta.yaml#L23).

From a quick look:
- `pytest` shouldn't be required to use `openpiv` (only for testing) and shouldn't be in `install_requires`.
- couldn't find `GitPython` imported anywhere
- I found `watermark` in `openpiv/tutorials/openpiv_pivuq.ipynb` but it doesn't seem mandatory to run `openpiv` either
- `tqdm` is imported in `openpiv/pyprocess3D.py` and should probably be in conda run requirements.

**Comment by alexlib** [comment]
> ### Comment:
> 
> While looking at another package (pyopenrivercam) that depends on this package, I noticed that the pip dependencies defined in [setup.py](https://github.com/OpenPIV/openpiv-python/blob/0bc247ea020ef7f59d94a53ec951f684c448b717/setup.py#L21) don't match the ones defined for the conda package in [meta.yaml](https://github.com/conda-forge/openpiv-feedstock/blob/449741f5091a54f09a5cb821fba01aa252b4c0f4/recipe/meta.yaml#L23).
> 
> From a quick look:
> 
>     * `pytest` shouldn't be required to use `openpiv` (only for testing) and shouldn't be in `install_requires`.
> 
>     * couldn't find `GitPython` imported anywhere
> 
>     * I found `watermark` in `openpiv/tutorials/openpiv_pivuq.ipynb` but it doesn't seem mandatory to run `openpiv` either
> 
>     * `tqdm` is imported in `openpiv/pyprocess3D.py` and should probably be in conda run requirements.

Could you please help us to fix the issues by a pull request? 
thanks
